exports.data ={
    "ReportDate": "2017-08-21T19:59:02.864534+07:00",
    "Orders": [
        {
            "Id": 216,
            "OrderId": 1560,
            "OrderDate": "2017-08-21T16:25:58",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 140.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 2.00,
            "ItemDiscount": 0.00,
            "Vat": 0.00,
            "GrandTotal": 138.00,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 138.00,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "11"
        },
        {
            "Id": 219,
            "OrderId": 1561,
            "OrderDate": "2017-08-21T16:49:19",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 390.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 39.00,
            "ItemDiscount": 0.00,
            "Vat": 24.57,
            "GrandTotal": 375.57,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 375.57,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        },
        {
            "Id": 220,
            "OrderId": 1562,
            "OrderDate": "2017-08-21T16:49:27",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        },
        {
            "Id": 221,
            "OrderId": 1563,
            "OrderDate": "2017-08-21T16:49:34",
            "IsDeleted": false,
            "IsOnTheHouse": false,
            "User": "rice",
            "PaymentType": "Cash",
            "ShiftWork": "Shift 1",
            "SubTotal": 480.00,
            "ServiceCharge": 0.00,
            "ServiceChargeIncluded": 0.0,
            "Rounding": 0.0,
            "Discount": 48.00,
            "ItemDiscount": 0.00,
            "Vat": 30.24,
            "GrandTotal": 462.24,
            "CardCharge": 0.0,
            "PaymentMethod": 0,
            "Received": 462.24,
            "Change": 0.00,
            "CustomerCount": 2,
            "Table": "12"
        }
    ],
    "DeletedOrders": [],
    "DeletedGrandTotal": 0.0,
    "SummaryPaymentType": [
        {
            "Name": "Cash",
            "Amount": 1438.05,
            "Quantity": 4.0
        }
    ],
    "SubTotal": 1490.00,
    "ServiceCharge": 0.00,
    "ServiceChargeIncluded": 0.0,
    "Rounding": 0.0,
    "Discount": 137.00,
    "ItemDiscount": 0.00,
    "Vat": 85.05,
    "GrandTotal": 1438.05,
    "CardCharge": 0.0,
    "PaymentMethod": 0,
    "Received": 0.0,
    "Change": 0.0,
    "CustomerCount": 8
}
